export { default as CartIcon } from './CartIcon'
export { default as DeleteIcon } from './DeleteIcon'
export { default as NextIcon } from './NextIcon'
export { default as PrevIcon } from './PrevIcon'
export { default as CloseIcon } from './CloseIcon'
export { default as PlusIcon } from './PlusIcon'
export { default as MinusIcon } from './MinusIcon'
